/** @type {{ [char: string]: [number, number] }} */
export const glyphMap = {
  a: [0, 0],
  b: [0, 1],
  c: [2, 5],
  d: [0, 3],
  e: [0, 4],
  f: [0, 5],
  g: [2, 6],
  h: [0, 7],
  i: [0, 8],
  j: [2, 7],
  k: [0, 10],
  l: [1, 0],
  m: [1, 1],
  n: [1, 2],
  o: [1, 3],
  p: [1, 4],
  q: [1, 5],
  r: [1, 6],
  s: [1, 7],
  S: [2, 4],
  t: [1, 8],
  u: [1, 9],
  v: [1, 10],
  x: [2, 8],
  y: [2, 2],
  z: [2, 3],
  "'": [3, 0],
  "-": [3, 1],
  " ": [3, 10],
  "\n": [3, 10],
};

export const classes = {
  "'": "apos",
  "-": "port",
  "\n": "break",
};

export const exceptions = {
  b: "bo",
  c: "chu",
  d: "da",
  g: "gu",
  j: "je",
  k: "ka",
  l: "la",
  p: "po",
  q: "qu",
  t: "te",
  v: "vu",
  S: "ss",
  x: "xi",
};
